inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'coverage/**/*'
    - 'db/**/*'
    - 'lib/**/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'spec/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - './*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false
